'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { RequireAuth } from '@/components/RequireAuth';
import { TopNav } from '@/components/TopNav';
import { ActionButton } from '@/components/shared';
import { galleryApi, publishStudioApi, studioApi } from '@/lib/api-client';
import type { GalleryItem } from '@/types/api';

type Finding = { finding_id?: string; code?: string; status?: string; severity?: string; message?: string; evidence_refs?: string[]; shot_refs?: string[]; start_ms?: number; end_ms?: number };
type Analysis = { analysis_id?: string; video_probe?: { duration_ms?: number; has_audio?: boolean }; statistics?: { shot_count?: number; average_shot_duration_ms?: number; cuts_per_minute?: number }; quality_report?: { status?: string; findings?: Finding[] }; shots?: Array<{ shot_id?: string; start_ms?: number }> };
type Comparison = { dimensions?: Record<string, { expected?: unknown; observed?: unknown; status?: string }> };
type Feedback = { finding_id?: string; target?: string; suggested_action?: string };

const statusText: Record<string, string> = { PASS: '符合', WARN: '部分符合', FAIL: '不符合', NOT_EVALUABLE: '无法评估', SKIPPED: '未检查' };
const targetText: Record<string, string> = { NARRATIVE: '故事', SCENE_BLUEPRINT: '场景', SHOT_PLAN: '分镜', ASSET_SELECTION: '素材', TIMING: '节奏', AUDIO: '音频', SUBTITLE: '字幕', RENDER: '渲染' };
const categoryText: Record<string, string> = { MEDIA_VALIDITY: '媒体完整性', AUDIO_STREAM_MISSING: '音频', SHOT_STRUCTURE: '镜头结构', PACING: '节奏', INTENT_ALIGNMENT: '目标匹配', NARRATIVE_ALIGNMENT: '叙事结构' };

function humanSeverity(value?: string) { return value === 'ERROR' || value === 'FAIL' ? '需要处理' : value === 'WARN' ? '建议检查' : '通过'; }
function displayValue(value: unknown) { if (value === undefined || value === null || value === '') return '未提供'; if (Array.isArray(value)) return value.join('、') || '未提供'; return String(value); }

export default function AnalysisPage() {
  const [assets, setAssets] = useState<GalleryItem[]>([]); const [selectedId, setSelectedId] = useState(''); const [loading, setLoading] = useState(true); const [running, setRunning] = useState(false); const [result, setResult] = useState<Analysis | null>(null); const [comparison, setComparison] = useState<Comparison | null>(null); const [feedback, setFeedback] = useState<Record<string, Feedback>>({}); const [referenceResult, setReferenceResult] = useState<Record<string, unknown> | null>(null); const [referenceRunning, setReferenceRunning] = useState(false); const [error, setError] = useState<string | null>(null); const playerRef = useRef<HTMLVideoElement>(null);
  useEffect(() => { galleryApi.list('long_video').then(setAssets).catch(err => setError(err instanceof Error ? err.message : '无法加载视频素材')).finally(() => setLoading(false)); }, []);
  const selected = useMemo(() => assets.find(item => item.item_id === selectedId), [assets, selectedId]); const sourcePath = selected && ((selected as GalleryItem & { source_path?: string }).source_path || selected.media_url); const quality = result?.quality_report; const findings = quality?.findings ?? [];
  function seekFinding(finding: Finding) { const start = finding.start_ms ?? result?.shots?.find(shot => finding.shot_refs?.includes(shot.shot_id ?? ''))?.start_ms; if (start !== undefined && playerRef.current) { playerRef.current.currentTime = start / 1000; void playerRef.current.play().catch(() => undefined); } }
  async function analyze() { if (!sourcePath || /^https?:\/\//.test(sourcePath)) { setError('该素材没有服务端可读路径。请先将视频保存到 HEVI 素材库。'); return; } setRunning(true); setError(null); setComparison(null); setFeedback({}); try { const analyzed = await studioApi.analyzeVideo(sourcePath); setResult(analyzed as Analysis); const intent = (selected as GalleryItem & { intent?: Record<string, unknown> })?.intent; if (intent) setComparison(await studioApi.compareVideo(sourcePath, intent) as Comparison); } catch (err) { setError(err instanceof Error ? err.message : '分析请求失败'); } finally { setRunning(false); } }
  async function suggest(finding: Finding) { const id = finding.finding_id || finding.code || `finding-${Object.keys(feedback).length}`; try { const proposal = await studioApi.createVideoFeedback({ finding_id: id, severity: finding.severity || finding.status || 'WARN', layer: finding.code || 'QUALITY', target: finding.code?.includes('AUDIO') ? 'AUDIO' : finding.code?.includes('SUBTITLE') ? 'SUBTITLE' : 'SHOT_PLAN', suggested_action: finding.message || '查看该质量问题并决定是否修改', evidence_refs: finding.evidence_refs || [] }); setFeedback(current => ({ ...current, [id]: proposal as Feedback })); } catch (err) { setError(err instanceof Error ? err.message : '建议生成失败'); } }
  async function analyzeReference() { const url = selected?.media_url; if (!url || !/^https?:\/\//.test(url)) { setError('参考片分析需要素材库中的可访问视频地址。'); return; } setReferenceRunning(true); setError(null); try { setReferenceResult(await publishStudioApi.mptReference({ url })); } catch (err) { setError(err instanceof Error ? err.message : '参考片分析请求失败'); } finally { setReferenceRunning(false); } }
  return <><TopNav /><RequireAuth><main className="product-page analysis-page"><div className="product-page__intro"><p className="product-page__eyebrow">视频分析</p><h1>看懂你的成片</h1><p>基于真实视频素材生成镜头时间轴、节奏与质量证据。</p></div>
    <section className="analysis-toolbar"><label htmlFor="analysis-asset">选择视频</label><select id="analysis-asset" value={selectedId} onChange={event => setSelectedId(event.target.value)} disabled={loading}><option value="">{loading ? '加载素材中…' : assets.length ? '选择一个视频素材' : '暂无可分析的视频素材'}</option>{assets.map(asset => <option key={asset.item_id} value={asset.item_id}>{asset.title}</option>)}</select><ActionButton onClick={analyze} loading={running} disabled={!selected}>开始分析</ActionButton></section>
    {error && <div className="product-alert product-alert--error">{error}</div>}{selected?.media_url && <video ref={playerRef} className="analysis-player" controls src={selected.media_url} />}
    {result && <><section className="analysis-result"><div className="analysis-result__header"><div><span className="analysis-result__kicker">概览</span><h2>{selected?.title}</h2></div><span className={`analysis-status analysis-status--${quality?.status}`}>{statusText[quality?.status || ''] || '已完成'}</span></div><div className="analysis-result__grid"><div><strong>镜头数量</strong><span>{result.statistics?.shot_count ?? '未提供'}</span></div><div><strong>平均镜长</strong><span>{result.statistics?.average_shot_duration_ms ? `${Math.round(result.statistics.average_shot_duration_ms)} ms` : '未提供'}</span></div><div><strong>节奏</strong><span>{result.statistics?.cuts_per_minute ? `${result.statistics.cuts_per_minute.toFixed(1)} cuts/min` : '未提供'}</span></div></div></section>
      <section className="quality-panel"><div className="panel-heading"><div><span className="analysis-result__kicker">质量检查</span><h2>{statusText[quality?.status || ''] || '分析完成'}</h2></div><span>{findings.length} 个发现</span></div>{findings.length ? findings.map(finding => { const id = finding.finding_id || finding.code || ''; return <button className="quality-finding" key={id} onClick={() => seekFinding(finding)}><span className={`finding-severity finding-severity--${finding.severity?.toLowerCase()}`}>{humanSeverity(finding.severity || finding.status)}</span><span><strong>{categoryText[finding.code || ''] || '质量问题'}</strong><small>{finding.message || '请查看技术详情'}</small><em>{finding.shot_refs?.join('、') || '整体'}</em></span><span className="finding-actions"><span>{finding.start_ms !== undefined ? `${Math.round(finding.start_ms / 1000)}s` : '定位'}</span><span onClick={event => { event.stopPropagation(); void suggest(finding); }}>建议修改</span></span></button>; }) : <p className="panel-empty">未发现需要处理的问题。</p>}</section>
      {Object.keys(feedback).length > 0 && <section className="feedback-panel"><span className="analysis-result__kicker">建议修改</span><h2>先查看，再决定是否应用</h2>{Object.values(feedback).map(item => <div className="feedback-item" key={item.finding_id}><strong>{targetText[item.target || ''] || '分镜'}</strong><span>{item.suggested_action}</span><button type="button">查看修改</button></div>)}</section>}
      <section className="comparison-panel"><div className="panel-heading"><div><span className="analysis-result__kicker">目标 vs 成片</span><h2>计划与实际</h2></div></div>{comparison ? <div className="comparison-grid">{Object.entries(comparison.dimensions || {}).map(([key, value]) => <div className="comparison-row" key={key}><strong>{key}</strong><span>计划：{displayValue(value.expected)}</span><span>实际：{displayValue(value.observed)}</span><em>{statusText[value.status || 'NOT_EVALUABLE'] || '无法评估'}</em></div>)}</div> : <p className="panel-empty">当前项目没有可用的结构化创作目标，暂时无法比较。</p>}</section><details className="technical-details"><summary>技术详情</summary><pre>{JSON.stringify(result, null, 2)}</pre></details></>}
    <section className="reference-card"><div><span className="analysis-result__kicker">参考片分析</span><h2>提取节奏与镜头结构</h2><p>只提取抽象制作特征，不复制原片内容。</p></div><ActionButton variant="secondary" onClick={analyzeReference} loading={referenceRunning} disabled={!selected}>应用为创作参考</ActionButton>{referenceResult && <details className="technical-details reference-card__result" open><summary>查看参考特征</summary><pre>{JSON.stringify(referenceResult, null, 2)}</pre></details>}</section>
    {!result && !error && <section className="analysis-empty"><div className="analysis-empty__icon">◌</div><h2>选择一个视频开始</h2><p>没有真实素材时不会生成占位结果。高级视觉理解暂不可用，但核心视频分析仍可使用。</p></section>}</main></RequireAuth></>;
}
