"""Canonical Production Graph persistence primitives.

The graph is the durable owner for director productions.  API modules may keep
an in-process projection for hot reads, but a projection is never the source
of truth.
"""

from hevi.production_graph.continuity import derive_continuity_constraints
from hevi.production_graph.contracts import (
    ConstraintChange,
    ExecutionNode,
    ExecutionPlan,
    PlanDecision,
    ProductionCommand,
    RepairDecision,
    ToolCall,
    inputs_hash,
)
from hevi.production_graph.domain import (
    Beat,
    CameraSpec,
    CanonicalShot,
    Character,
    CharacterState,
    ConstraintSeverity,
    ConstraintType,
    ContinuityConstraint,
    DirectorDecision,
    DirectorSession,
    DirectorSessionStatus,
    Episode,
    ExecutionAttempt,
    GenerationIntent,
    Keyframe,
    KeyframeRole,
    Location,
    LocationState,
    LookVariant,
    NarrativeEdge,
    NarrativeEdgeType,
    NarrativeEvent,
    NarrativeGraph,
    PlotThread,
    ProductionGraphSnapshot,
    ProductionMode,
    ProductionPlan,
    ProductionProject,
    ProductionRevision,
    ProjectStatus,
    Prop,
    PropState,
    ReadinessState,
    ReferenceBundle,
    ReferenceItem,
    ReferenceRole,
    RevisionPatch,
    RevisionPatchOperation,
    Scene,
    Season,
    Shot,
    ShotReadinessResult,
    ShotSize,
    SourceChunk,
    SourceDocument,
    SourceKind,
    SourceReference,
    TaskEnvelope,
    World,
    WorldRule,
)
from hevi.production_graph.ids import canonical_id, is_canonical_id, new_id, stable_id
from hevi.production_graph.keyframes import (
    KeyframeLockError,
    action_keyframes,
    lock_keyframe,
    replace_keyframe,
    validate_keyframes,
)
from hevi.production_graph.readiness import (
    ReadinessContext,
    ReadinessTransitionError,
    assert_dispatchable,
    evaluate_readiness,
    prepare_shot,
    transition_shot,
)
from hevi.production_graph.reference_views import (
    ReferenceViewSelection,
    select_reference_view,
    select_views_for_characters,
)
from hevi.production_graph.references import ReferenceLockError, add_reference, lock_reference
from hevi.production_graph.repository import ProductionGraphRepository

__all__ = [
    "ConstraintChange",
    "ConstraintSeverity",
    "ConstraintType",
    "ContinuityConstraint",
    "Beat",
    "CameraSpec",
    "CanonicalShot",
    "Character",
    "CharacterState",
    "DirectorDecision",
    "DirectorSession",
    "DirectorSessionStatus",
    "ExecutionAttempt",
    "ExecutionNode",
    "ExecutionPlan",
    "Episode",
    "GenerationIntent",
    "Keyframe",
    "KeyframeRole",
    "Location",
    "LocationState",
    "LookVariant",
    "NarrativeEdge",
    "NarrativeEdgeType",
    "NarrativeEvent",
    "NarrativeGraph",
    "PlotThread",
    "ProductionGraphSnapshot",
    "ProductionMode",
    "ProductionPlan",
    "ProductionProject",
    "ProductionRevision",
    "ReadinessContext",
    "ReadinessTransitionError",
    "PlanDecision",
    "Prop",
    "PropState",
    "ProjectStatus",
    "ReadinessState",
    "ReferenceBundle",
    "ReferenceItem",
    "ReferenceRole",
    "ProductionCommand",
    "ProductionGraphRepository",
    "RepairDecision",
    "RevisionPatch",
    "RevisionPatchOperation",
    "Scene",
    "Season",
    "Shot",
    "ShotReadinessResult",
    "ShotSize",
    "SourceChunk",
    "SourceDocument",
    "SourceKind",
    "SourceReference",
    "TaskEnvelope",
    "ToolCall",
    "World",
    "WorldRule",
    "ReferenceLockError",
    "ReferenceViewSelection",
    "KeyframeLockError",
    "action_keyframes",
    "add_reference",
    "canonical_id",
    "derive_continuity_constraints",
    "inputs_hash",
    "is_canonical_id",
    "lock_keyframe",
    "lock_reference",
    "new_id",
    "replace_keyframe",
    "select_reference_view",
    "select_views_for_characters",
    "stable_id",
    "assert_dispatchable",
    "evaluate_readiness",
    "prepare_shot",
    "transition_shot",
    "validate_keyframes",
]
