"""add_user_id_to_video_tasks

Revision ID: 014fa1589908
Revises: d8094b52852a
Create Date: 2026-06-14 23:42:16.908941

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '014fa1589908'
down_revision: str | None = 'd8094b52852a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_tasks', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_video_tasks_user_id'), 'video_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_tasks_user_id'), table_name='video_tasks')
    op.drop_column('video_tasks', 'user_id')
    # ### end Alembic commands ###
