"""create constraint_consumption_receipts table

P0-A: immutable record of constraint consumption lifecycle
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c0d1e2f3a4b5"
down_revision: str | None = "5f60718293a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "constraint_consumption_receipts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("production_id", sa.UUID(), nullable=False),
        sa.Column("revision_id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("constraint_id", sa.Text(), nullable=False),
        sa.Column("provider_id", sa.Text(), nullable=False),
        sa.Column("adapter_id", sa.Text(), nullable=False),
        sa.Column("stage", sa.Text(), nullable=False),
        sa.Column("mapping_type", sa.Text(), nullable=False),
        sa.Column("mapping_path", sa.Text(), nullable=False),
        sa.Column("payload_hash", sa.Text(), nullable=False),
        sa.Column("provider_request_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id", "constraint_id", "stage", "mapping_path"),
    )
    op.create_index(
        "ix_ccr_attempt", "constraint_consumption_receipts", ["attempt_id"]
    )
    op.create_index(
        "ix_ccr_constraint", "constraint_consumption_receipts", ["production_id", "revision_id", "constraint_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ccr_constraint", table_name="constraint_consumption_receipts")
    op.drop_index("ix_ccr_attempt", table_name="constraint_consumption_receipts")
    op.drop_table("constraint_consumption_receipts")
    # ### end Alembic commands ###
